// The toy figure and arrow models (Assets/Models/ConstructorFigure, ConstructorArrow, generated by
// Tools/generate_constructor_accessories.py) as solver boxes: each model's bounding box is its collision box, one collision
// margin taller so that a resting model touches the ground (contacts settle exactly one margin deep), like the brick.

using Unity.Mathematics;

namespace Phys.AvbdGpu.Siege
{
    /// <summary>Dimensions of the figure model (metres): faces +z, pivot at foot level under the body's axis.</summary>
    public static class Figure
    {
        public const float Width = 0.354f;                 // hand to hand (x)
        public const float Height = 0.48f;                 // feet to the top of the head stud (y)
        public const float Depth = 0.12f;                  // head and feet (z)
        /// <summary>The bounding box centre is 3 mm in front of the pivot (the feet reach further forward than the head).</summary>
        public const float DepthCenter = 0.003f;
    }

    /// <summary>Dimensions of the arrow model (metres): a flat plate pointing +z, pivot at the centre of its base.</summary>
    public static class ArrowModel
    {
        public const float Width = 0.15f;                  // head (x)
        public const float Thickness = 0.018f;             // (y)
        public const float Length = 0.3f;                  // (z)
    }

    /// <summary>How the models map to solver bodies: scale, masses and the box / mesh geometry.</summary>
    public struct SiegeSpec
    {
        /// <summary>Solver metres per model metre (the castle's BrickScale).</summary>
        public float Scale;
        /// <summary>The solver's collision margin.</summary>
        public float Margin;
        /// <summary>Masses (kg); the cannonball is light enough to lodge in a wall rather than cross the courtyard.</summary>
        public float UnitMass, ArrowMass, BallMass, BoltMass;
        public float Friction;
        /// <summary>Cannonball and magic-bolt cube sizes (model metres).</summary>
        public float BallCube, BoltCube;

        public static SiegeSpec Default => new SiegeSpec
        {
            Scale = 5f, Margin = 0.01f, UnitMass = 1f, ArrowMass = 0.02f, BallMass = 5f, BoltMass = 0.1f, Friction = 0.6f,
            BallCube = 0.12f, BoltCube = 0.06f,
        };

        public float3 UnitBoxSize => new float3(Figure.Width * Scale, Figure.Height * Scale + Margin, Figure.Depth * Scale);
        /// <summary>The figure's pivot relative to its collision box centre (body space).</summary>
        public float3 UnitMeshOffset => new float3(0f, -(Figure.Height * Scale - Margin) * 0.5f, -Figure.DepthCenter * Scale);
        public float UnitDensity => UnitMass / (UnitBoxSize.x * UnitBoxSize.y * UnitBoxSize.z);
        /// <summary>Height of the box centre above the ground when the figure stands (one margin deep).</summary>
        public float UnitStandHeight => UnitBoxSize.y * 0.5f - Margin;

        public float3 ArrowBoxSize => new float3(ArrowModel.Width * Scale, ArrowModel.Thickness * Scale + Margin, ArrowModel.Length * Scale);
        public float3 ArrowMeshOffset => new float3(0f, -(ArrowModel.Thickness * Scale - Margin) * 0.5f, 0f);
        public float ArrowDensity => ArrowMass / (ArrowBoxSize.x * ArrowBoxSize.y * ArrowBoxSize.z);

        public float3 BallSize => BallCube * Scale;
        public float BallDensity => BallMass / (BallSize.x * BallSize.y * BallSize.z);
        public float3 BoltSize => BoltCube * Scale;
        public float BoltDensity => BoltMass / (BoltSize.x * BoltSize.y * BoltSize.z);
    }
}
